# Generated by Django 5.2.1 on 2025-08-07 04:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='banner_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
